config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :students
  resources :courses
  resources :classrooms, only: [:new, :create]
  resources :home, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :student, inverse_of: :classrooms
  belongs_to :course, inverse_of: :classrooms

  validates :entry_at, presence: true
  validates :student, presence: true
  validates :course, presence: true
  validates :student_id, uniqueness: { scope: :course_id }
end

app/models/course.rb
class Course < ApplicationRecord
	has_enumeration_for :status, create_helpers: true

	has_many :classrooms, inverse_of: :course, dependent: :destroy

  	has_many :students, through: :classrooms

	validates :name, presence: true, length: { maximum: 45 },uniqueness: true
  	validates :description, presence: true, length: { maximum: 45 }
  	validates :status, presence: true, length: { maximum: 1 }
end

app/models/student.rb
class Student < ApplicationRecord

	has_enumeration_for :status, create_helpers:  true

	has_many :classrooms, inverse_of: :student, dependent: :destroy

  	has_many :courses, through: :classrooms

	validates :name, presence: true, length: { maximum: 45 }
	validates :register_number, presence: true, length: { maximum: 45 }, uniqueness: true
	validates :status, presence: true, length: { maximum: 1 }
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    redirect_to new_classroom_path
  end

  def new
    @classroom = Classroom.new
  end

  def create
  	@classroom = Classroom.new(classroom_params)
    if @classroom.save
      flash[:notice] = t('flash.actions.create.notice', resource_name: t('classroom'))
    end
    respond_with @classroom, location: -> { courses_path }
  end

  # private methods

  private

  def classroom_params
    params.require(:classroom).permit(:student_id, :course_id, :entry_at)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	respond_to :html

	def index
		@courses = Course.all
	end

	def show
		@course = Course.find(params[:id])
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)
		if @course.save
	      flash[:notice] = t('flash.actions.create.notice', resource_name: @course.name)
	    end
	    respond_with @course, location: -> { courses_path }
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])
		if @course.update_attributes(course_params)
			flash[:notice] = t('flash.actions.update.notice', resource_name: @course.name)
	    end
	    respond_with @course
	end

	def destroy
		@course = Course.find(params[:id])
	    if @course.destroy
	      flash[:notice] = t('flash.actions.destroy.notice', resource_name: @course.name)
	    end
	    respond_with @course, location: -> { courses_path }
	 end

	private

	def course_params
		params.require(:course).permit(:name, :description, :status)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	respond_to :html

	def index
		@students = Student.all
	end

	def show
		@student = Student.find(params[:id])
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
		if @student.save
			flash[:notice] = t('flash.actions.create.notice', resource_name: @student.name)
		end
		respond_with @student, location: -> { students_path }
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])
		if @student.update(student_params)
			flash[:notice] = t('flash.actions.update.notice', resource_name: @student.name)
		end
		respond_with @student
	end

	def destroy
		@student = Student.find(params[:id])
		if @student.destroy
			flash[:notice] = t('flash.actions.destroy.notice', resource_name: @student.name)
		end
		respond_with @student, location: -> { students_path } 
	end

	private

	def student_params
		params.require(:student).permit(:name, :register_number, :status)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Kursai"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
  def students_map
    Student.all.map { |s| [s.name, s.id] }
  end

  def courses_map
    Course.all.map { |c| [c.name, c.id] }
  end
end

app/views/classrooms/_form.html.slim
= form_for @classroom do |f|
	fieldset.form-group
		= f.label :student
		= f.select :student_id, students_map, {}, { class: 'form-control' }
	fieldset.form-group
		= f.label :course
		= f.select :course_id, courses_map, {}, { class: 'form-control' }
	fieldset.form-group
		= f.hidden_field :entry_at, value: DateTime.now
		= f.submit yield(:button_text), class: 'btn btn-primary'

app/views/classrooms/edit.html.slim
= provide(:title, t('.edit_classroom'))
= provide(:button_text, t('.button_edit'))

h1
	= t('.edit_classroom')

= render 'form'

app/views/classrooms/new.html.slim
= provide(:title, t('.new_classroom'))
= provide(:button_text, t('.button_new'))

h1
	= t('.new_classroom')

= render 'form'

app/views/courses/_form.html.slim
= form_for @course do |f|
    fieldset.form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
    fieldset.form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'
    fieldset.form-group
        = f.label :status
        = f.select :status, Status.to_a, {}, { class: 'form-control' }
    fieldset.form-group
        = f.submit yield(:button_text), class: 'btn btn-primary'

app/views/courses/edit.html.slim
= provide(:title, t('.edit_course'))
= provide(:button_text, t('.button_edit'))

h1
 =t('.edit_course')

= render 'form'

app/views/courses/index.html.slim
= provide(:title, t('.courses'))

h1 
	= t('.courses')

.row
  .col-xs-12
    .table-responsive
      table.table
        table.table
          thead
            tr
              th
                = Course.human_attribute_name(:name)
              th
                = Course.human_attribute_name(:status)
              th
                = t('actions')
          tbody
            - @courses.each do |course|
                tr
                  td
                    = link_to course.name, course_path(course)
                  td
                    = link_to course.status_humanize, course_path(course)
                  td
                    = link_to edit_course_path(course), class: "btn btn-success btn-xs" do
                      span.glyphicon.glyphicon-pencil
                    = link_to course_path(course),
                      data: { confirm: t('remove_register_confirmation') },
                      method: :delete, class: "btn btn-danger btn-xs" do
                      span.glyphicon.glyphicon-trash

.row
	.col-xs-12
  		= link_to t('add'), new_course_path, class: 'btn btn-primary'

app/views/courses/new.html.slim
= provide(:title, t('.new_course'))
= provide(:button_text, t('.button_edit'))

h1
 =t('.new_course')

= render 'form'

app/views/courses/show.html.slim
= provide(:title, t('.show_course'))
- students = @course.students

h1
  = t('.course')

.row
  .col-xs-2
    =Course.human_attribute_name(:name)
  .col-xs-2
    =@course.name

.row
  .col-xs-2
    =Course.human_attribute_name(:description)
  .col-xs-2
    =@course.description

.row
  .col-xs-2
    = Course.human_attribute_name(:status)
  .col-xs-2
    = @course.status_humanize

- if students.present?
  h3
    = t('.students')

  .row
    .col-xs-6
      .table-responsive
        table.table
          table.table
            thead
              tr
                th
                  = Student.human_attribute_name(:register_number)
                th
                  = Student.human_attribute_name(:name)
               
              tbody
                - students.each do | student |
                  tr
                    td
                      = link_to student.register_number, student_path(student)
                    td
                      = link_to student.name, student_path(student)
                    

app/views/home/index.html.slim
= provide(:title, t('.home'))
.center.jumbotron
	h1 
		=t('.company')
	h2
		=t('.legend')

app/views/layouts/_footer.html.slim
footer class="footer"
	small
		p
			=t('.development_by')

app/views/layouts/_header.html.slim
navbar.navbar-fixed-top.navbar-inverse
        .navbar-header
          button.navbar-toggle data-target="#system-navbar" data-toggle="collapse" type="button"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Kursai", root_path, class: 'navbar-brand'

        #system-navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              = link_to Student.model_name.human, students_path
            li
              = link_to Course.model_name.human, courses_path
            li
              = link_to Classroom.model_name.human, new_classroom_path

app/views/layouts/_shim.html.slim
javascript:
	<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
		</script>
	<![endif]-->

app/views/layouts/application.html.slim
doctype html
html
	head
		title = full_title(yield(:title))
		= stylesheet_link_tag 'application', media:'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tag
	body
		= render 'layouts/header'
		.container
			- if flash[:notice]
			  .alert.alert-success = flash[:notice]

			- if flash[:alert]
			  .alert.alert-danger = flash[:alert]

			= yield
			= render  'layouts/footer'

app/views/students/_form.html.slim
= form_for @student do |f|
	fieldset.form-group
		= f.label :name
		= f.text_field :name, class: "form-control"
	fieldset.form-group
		= f.label :register_number
		= f.text_field :register_number, class: "form-control"
	fieldset.form-group
		= f.label :status
		= f.select :status, Status.to_a, {}, { class: 'form-control'}
	fieldset.form-group
		= f.submit yield(:button_text), class: "btn btn-primary"

app/views/students/edit.html.slim
= provide(:title, t('.edit_student'))
= provide(:button_text, t('.button_edit'))

h1
	= t('.edit_student')

= render 'form'

app/views/students/index.html.slim
= provide(:title, t('.students'))

h1 
	= t('.students')

.row
	.col-xs-12
		.table-responsive
			table.table
				table.table
					thead
						tr
							th
								= Student.human_attribute_name(:name)
							th
								=Student.human_attribute_name(:status)
							th
								= t('action')
						tbody
							- @students.each do | student |
								tr
									td
										= link_to student.name, student_path(student)
									td 
										= link_to student.status_humanize, student_path(student) 
									td
										= link_to edit_student_path(student), class: "btn btn-success btn-xs" do
                      						span.glyphicon.glyphicon-pencil
										= link_to student_path(student), data: { confirm: t('remove_register_confirmation') }, method: :delete, class: "btn btn-danger btn-xs" do
                      						pan.glyphicon.glyphicon-trash

.row
	.col-xs-12
  		= link_to t('add'), new_student_path, class: 'btn btn-primary'

app/views/students/new.html.slim
= provide(:title, t('.new_student'))
= provide(:button_text, t('.button_new'))

h1
 = t('.new_student')

= render 'form'

app/views/students/show.html.slim
= provide(:title, t('.show_student'))

- courses = @student.courses

h1
	= t('.student')

.row
	.col-xs-2
		=Student.human_attribute_name(:name)
	.col-xs-2
		= @student.name

.row
	.col-xs-2
		= Student.human_attribute_name(:register_number)
	.col-xs-2
		= @student.register_number

.row
	.col-xs-2
		= Student.human_attribute_name(:status)
	.col-xs-2
		= @student.status_humanize

- if courses.present?
  h3
    = t('.courses')
  .row
	  .col-xs-12
	    .table-responsive
	      table.table
	        table.table
	          thead
	            tr
	              th
	                = Course.human_attribute_name(:name)
	              th
	                = Course.human_attribute_name(:status)
	          tbody
	            - courses.each do |course|
	                tr
	                  td
	                    = link_to course.name, course_path(course)
	                  td
	                    = link_to course.status_humanize, course_path(course)